### ISSUE TITLE
missing part of the code for the test set

### ISSUE THREAD

**Issue by CSY-siyuan** [seorim0/ResU_Dense#1]
I have reviewed your code and found that the validation set and test set are the same part of the dataset. Additionally, the code for the test set is not provided. Please provide some explanations. Thank you."

**Comment by seorim0** [comment]
Hi! Thank you for your interest in our research.
I've added code for testing. (test_interface.py)

I hope the code helps you.

**Comment by CSY-siyuan** [comment]
Thank you, this is very helpful to me.It would be even better if you have a Python file for preprocessing ECG data.

**Comment by seorim0** [comment]
It would be much more helpful to refer to the codes below for preprocessing ECG data!

- https://neuropsychology.github.io/NeuroKit/functions/ecg.html
- https://moody-challenge.physionet.org/2021/results/

If there is any specific code you want in our project, please tell me :)
